### ISSUE TITLE
Add semver pattern support for gardener extensions

### ISSUE THREAD

**Issue by schrodit** [gardener/test-infra#188]
>Instead of using hard coded values here it may be a good idea to use semver ranges. Gardener/Gem offers great support for this use case. 

Add support to specify semver ranges in the test configuration of the tm bot like it is implemeneted in the g/gems.

It should be possible to specify the following exmaple:
```
# configure default values for pull request tests
test:

  # gardener extensions to be deployed
  # will be merged with the default extensions defined in garden setup.
  gardener-extensions:
    value: |
      os-coreos: 
          repo: "https://github.com/gardener/gardener-extensions.git"
          version": "1.0.x"
```

**Implementation**
Reuse the extension gems to resolve th correct version.
We would need to replace the git tolling with GitHub api requests.
