### ISSUE TITLE
Testrun was unable to run if a step finds no testrun

### ISSUE THREAD

**Issue by schrodit** [gardener/test-infra#270]
**What happened**:

Testmachinery silently errors in the workflow with the following error message
` message: 'invalid spec: templates.testrun.tasks.delete-shoot-delete-testflow templates.delete-shoot-delete-testflow
    inputs.artifacts.repo was not supplied'`

The problem with the testrun is that the step before `delete-shoot` does not match a test-def.

```yaml
steps:
- name: create
    dependsOn: [ generate-provider ]
    definition:
      name: create-shoot
  - name: tests
    dependsOn: [ create ]
    definition:
      label: no-test
      continueOnError: true
  - name: delete
    dependsOn: [ tests ]
    definition:
      name: delete-shoot
```

**What you expected to happen**:

test should ignore the step if no tests can be found and only execute the found ones.
We may want to define min required 1 on labels.
