### ISSUE TITLE
rotate-kubeconfig integration tests breaks later tests

### ISSUE THREAD

**Issue by dguendisch** [gardener/test-infra#322]
**How to categorize this issue?**
/area testing
/kind bug
/priority normal

**What happened**:
When promoting the integration test `should rotate kubeconfig for a shoot cluster` in https://github.com/gardener/gardener/pull/3300 from beta to default, we missed to understand that this tests will "invalidate" the kubeconfigs used by subsequent tests.
The attempt to overcome this with https://github.com/gardener/gardener/pull/3326 unfortunately doesn't work, as the kubeconfigs from TestMachinery are currently not meant to be "updated" via intermediate steps, hence all tests will only get the kubeconfigs from the create-shoot step, see e.g. this generated argo task for the e2e tests:

```
      - arguments:
          artifacts:
          - from: '{{tasks.create-shoot-create-testflow.outputs.artifacts.kubeconfigs}}'
            name: kubeconfigs
          ...
        dependencies:
        - shoot-default-serial-test-suite-tests-default-testflow
        name: e2e-fast-e2e-testflow
```

**What you expected to happen**:
Maybe kubeconfigs should be allowed to be overwritten by intermediate steps.
