### ISSUE TITLE
Wrong additionalLocations in flavors lead to rejected Testruns

### ISSUE THREAD

**Issue by dguendisch** [gardener/test-infra#378]
A flavor snippet like this:
```
- provider: gcp
  additionalLocations:
  - type: git
  allowPrivilegedContainers: false
```

Leads to a rendered Testrun that contains a location without any repo and revision and is therefore consequently rejected by the admission webhook.
```
admission webhook \"validate-testrun.tm.garden.cloud\" denied the request: [spec.locationSets[0].locations[84].repo: Required value: repo has to be defined for git TestDefinition locations, spec.locationSets[0].locations[84].revision: Required value: revision has to be defined for git TestDefinition locations]"
```

The flavor parsing should instead immediately reject meaningless `additionalLocations` fields (that have no repo and revision but just a type).
