### ISSUE TITLE
Support more machine image version patterns in flavors

### ISSUE THREAD

**Issue by dguendisch** [gardener/test-infra#380]
In flavors we can today specify either a fixed machine image version or `latest`.
For certain tests we want to test all non-deprecated versions of a certain machine image.
It would be helpful if the flavors would support such a version specification similar to how it was done for the k8sVersions (were we support `latest` and semver).

Example:
```
      machine:
        type: n1-standard-2
        image:
          name: gardenlinux
          version: "*"
          filterDeprecatedVersions: true
```
