### ISSUE TITLE
Add support for global artifacts.

### ISSUE THREAD

**Issue by schrodit** [gardener/test-infra#80]
# Issue
As a user I want to use global artifacts from serial steps as input source.

# Description
Currently serial steps write their output to the global artifact registry.
To consume this kind of artifacts a special argo reference is needed.
Therefore another parameter (like `globalInput`) needs to be introduced that specifies the usage of a global artifact.

This is also needed to share files between the `testflow` and the `onExit` flow.

```yaml
testflow:
- name: demo-step
  definition:
      name: demo
- name: label-step
  globalInput: true
  dependsOn: [ demo-step ]
  definition:
      label: default
```
