### ISSUE TITLE
Add support for artifactFrom

### ISSUE THREAD

**Issue by schrodit** [gardener/test-infra#83]
### Problem
As a user a want to specify specific steps to get the input artifact.
This feature give the opportunity to create shoot --> update gardener to a new version --> test the same shoot again.

### Description:

Add a `artifactFrom`parameter to the step configuration so that specific steps can be referenced as input sources.
⚠️ Only steps with `definition.name` are allowed as `definition.labels` could include multiple steps.

```yaml
testflow:
- name: step1
  definition:
    name: test
- name: step2
  definition:
    label: default
  artifactFrom: step1
```
